lib/elmverse_web/router.ex
defmodule ElmverseWeb.Router do
  use ElmverseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElmverseWeb do
    pipe_through :browser

    get "/", IndexController, :index

    get "/repo/:elm_ver", RepositoryController, :index
    get "/repo/:elm_ver/:pub/:pkg/:ver", RepositoryController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElmverseWeb do
  #   pipe_through :api
  # end
end

lib/elmverse_web/templates/index/index.html.eex
<%= for repo <- @repositories do %>
<div class="columns">
    <div class="column is-full">
        <div style="margin-top: 10px"></div>
        <div class="card">
            <a href="<%= Routes.repository_path(@conn, :index, repo.elm_ver) %>">
                <header class="card-header">
                    <p class="card-header-title"><%= repo.elm_ver %></p>
                </header>
                <div class="card-content">
                    <table class="table is-fullwidth">
                        <tbody>
                        <tr>
                            <td>Packages</td>
                            <td><%= repo.pkg_count %></td>
                        </tr>
                        <tr>
                            <td>Last Updated</td>
                            <td><%= fmt_last_update(repo) %></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </a>
        </div>
    </div>
</div>
<% end %>
<div class="columns">
    <div class="column">
        <p class="is-info">MOST LOOKUPS</p>
    </div>

    <div class="column">
        <p class="is-info">NEW PACKAGES</p>
    </div>

    <div class="column">
        <p class="is-info">RECENTLY UPDATED</p>
    </div>
</div>